#!/usr/bin/env node

/*
 * pass - create a strong password that's *easy* to regenerate from *memory*
 *
 * First, setup "pass" by exporting environment variable PASS_SALT to a word
 * you're very likely to remember. Use the same word for every installation!
 *
 * Second, put the "pass" command somewhere in your PATH e.g. your "bin" folder.
 *
 * Third, run "pass" by writing a password phrase to the command "pass" like so:
 *
 *
 * > pass
 * my secret phrase
 *
 * WARNING: using default salt "Himalayan"
 *          please set your env variable PASS_SALT
 *
 * my secret phrase ===> QYYL96XiEs$gWmJtZJDBY9t$OMZxjmBGjDgqG4xo
 *
 *
 * (If you didn't setup the PASS_SALT environment variable, you should see this)
 *
 * Note: passwords are at least 30 characters long, and include 2 special chars.
 */

const DEFAULT_SALT = 'Himalayan',
      SPECIAL_CHAR = '~!@#$%^&*',
      MIN_PASSWORD_LENGTH = 30,
      crypto = require('crypto'),
      readline = require('readline');

var rd = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

var interval = null;
rd.on('line', function(line) {
  if (line.length === 0) {
    console.error('please enter a pass word or phrase');
  } else {
    if (interval) { clearInterval(interval); }

    pass(line);

    interval = setInterval(function() { console.log(); process.exit(0); }, 500);
  }
});

// reverse a string
function reverse(s) {
  return s.split('').reverse().join('');
}

// insert a special character
function special(s) {
  var code = 0;
  for (var i = 0; i < s.length; i++) {
    code += s.charCodeAt(i);
  }
  var char = SPECIAL_CHAR[ code % SPECIAL_CHAR.length ],
      left = code % s.length;

  return s.substr(0, left) + char + s.substr(left);
}

function pass(word) {
  const salt = process.env.PASS_SALT || DEFAULT_SALT,
        pass = crypto.createHmac('sha256', salt)
                     .update(word)
                     .digest('base64')
                     .replace(/[^\w]/g, '');

  if (salt === DEFAULT_SALT) {
    console.log(`\nWARNING: using default salt "${DEFAULT_SALT}"`);
    console.log('         please set your env variable PASS_SALT');
  }

  if (pass.length >= MIN_PASSWORD_LENGTH) {
    var withTwoSpecialCharacters = reverse(special(special(pass)));
     console.log('\n' + word + ' ===> ' + withTwoSpecialCharacters);
  } else {
    console.error(`\nunexpected password length ${pass.length}\n`);
  }
}
 
// EOF
